name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install git 
        run: sudo apt-get install -y git

      - name: Install heroku cli
        run: sudo snap install --classic heroku

      - name: Add heroku git remote
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/softwire-yahtzee.git HEAD:main

      - name: Deploy to heroku
        run: git push heroku main