name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install git 
        run: sudo apt-get install -y git
      
      - name: Set a git username
        run: git config --global user.name "CI"

      - name: install heroku cli
        run: sudo snap install --classic heroku

      - name: add heroku git remote
        run: heroku git:remote -a softwire-yahtzee

      - name: deploy to heroku
        run: git push heroku main